# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='competitor',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u0422\u043e\u0432\u0430\u0440', 'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440\u044b'},
        ),
        migrations.AlterModelOptions(
            name='competitor',
            options={'verbose_name': '\u041a\u043e\u043d\u043a\u0443\u0440\u0435\u043d\u0442', 'verbose_name_plural': '\u041a\u043e\u043d\u043a\u0443\u0440\u0435\u043d\u0442\u044b'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '\u0413\u0440\u0443\u043f\u043f\u0430', 'verbose_name_plural': '\u0413\u0440\u0443\u043f\u043f\u044b'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '\u0417\u0430\u0434\u0430\u043d\u0438e', 'verbose_name_plural': '\u0417\u0430\u0434\u0430\u043d\u0438\u044f'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='shop',
        ),
        migrations.AddField(
            model_name='article',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Competitor'),
        ),
        migrations.AddField(
            model_name='article',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='article',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Group'),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo_path',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
