# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_mobiledevices'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('uuid', models.CharField(max_length=250)),
                ('phone_number', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': '\u041c\u043e\u0431\u0438\u043b\u044c\u043d\u043e\u0435 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u043e',
                'verbose_name_plural': '\u041c\u043e\u0431\u0438\u043b\u044c\u043d\u044b\u0435 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0430',
            },
        ),
        migrations.RemoveField(
            model_name='mobiledevices',
            name='task',
        ),
        migrations.DeleteModel(
            name='MobileDevices',
        ),
        migrations.AddField(
            model_name='task',
            name='mobileDevice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.MobileDevice'),
        ),
    ]
