# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20160906_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='in_work',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
