# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_in_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='begin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
