# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_mobiledevice_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='begin_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(),
        ),
    ]
