# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20160908_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tasktype',
            field=models.CharField(choices=[(b'm', b'\xd0\x9c\xd0\xbe\xd0\xbd\xd0\xb8\xd1\x82\xd0\xbe\xd1\x80\xd0\xb8\xd0\xbd\xd0\xb3 \xd1\x86\xd0\xb5\xd0\xbd'), (b'site', b'\xd0\x9c\xd0\xbe\xd0\xbd\xd0\xb8\xd1\x82\xd0\xbe\xd1\x80\xd0\xb8\xd0\xbd\xd0\xb3 \xd1\x81\xd0\xb0\xd0\xb9\xd1\x82\xd0\xbe\xd0\xb2')], default='m', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='uuid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='completedate',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
