# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20160908_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_action',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='latitude',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='longitude',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
