# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='quality',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='weight',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
